/** Phase 12 tunables for meals, happiness, influence, careers. */
export const Phase12Balance = {
  mealCost: 1,
  mealHungerRecover: 40,
  /** Slightly slower hunger so early food stress is less of a plague. */
  hungerRisePerHour: 8,
  hungerInterruptAt: 45,
  /** Hunger at/above this *may* mark a subject sick (see hungerSickChance). */
  sickAtHunger: 90,
  /** Chance to catch hunger-sickness when crossing the threshold (per hourly tick). */
  hungerSickChance: 0.15,
  /** Hunger at/above this is fatal without food. */
  dieAtHunger: 100,
  eatDurationMs: 1600,
  keepInfluenceRadius: 280,
  paradeCooldownMs: 180_000,
  paradeDurationMs: 28_000,
  paradeHappiness: 8,
  lineStreetHappiness: 6,
  tavernMealHappiness: 3,
  chatHappiness: 2,
  festivalHappiness: 5,
  jesterAuraRange: 64,
  jesterHappinessPerTick: 1,
  gypsyEntertainRange: 80,
  gypsyEntertainHappiness: 2,
  defectHappinessThreshold: 20,
  defectHoursNeeded: 6,
  pregnancyDays: 4,
  childPromoteAge: 14,
  elderAge: 55,
  defaultLifespan: 72,
  royalLifespan: 80,
  arrestBountyGold: 3,
  careerCosts: {
    guard: 18,
    soldier: 22,
    archer: 22,
    knight: 40,
    general: 65,
    bishop: 50,
    witch_hunter: 45,
    dungeon_keeper: 30,
    executioner: 35,
    jester: 28,
    physician: 35,
  } as Record<string, number>,
} as const;
